# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=500)),
                ('brand_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('useful_links', models.CharField(blank=True, max_length=2000, null=True)),
                ('dimensions', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edgeType', models.IntegerField()),
                ('device_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device1_device', to='plan_surgery.Device')),
                ('device_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device2_device', to='plan_surgery.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fields', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('canvas', models.CharField(max_length=20000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(to='plan_surgery.Device')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=200)),
                ('field_2', models.CharField(max_length=200)),
                ('comparator', models.CharField(max_length=2)),
                ('device_type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type_1_typedependency', to='plan_surgery.DeviceType')),
                ('device_type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type_2_typedependency', to='plan_surgery.DeviceType')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_surgery.DeviceType'),
        ),
    ]
