# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan_surgery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edgeType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fields', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=200)),
                ('field_2', models.CharField(max_length=200)),
                ('comparator', models.CharField(max_length=2)),
                ('device_type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type_1_typedependency', to='plan_surgery.DeviceType')),
                ('device_type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type_2_typedependency', to='plan_surgery.DeviceType')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='useful_links',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_surgery.DeviceType'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='devices',
            field=models.ManyToManyField(to='plan_surgery.Device'),
        ),
        migrations.AddField(
            model_name='devicedependency',
            name='device_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device1_device', to='plan_surgery.Device'),
        ),
        migrations.AddField(
            model_name='devicedependency',
            name='device_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device2_device', to='plan_surgery.Device'),
        ),
    ]
