# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_surgery', '0002_surgery_remaining_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='remaining_dimensions',
        ),
    ]
